//@GeneratedCode
namespace QuickTemplate.Logic.Contracts.Test
{
    ///
    /// Generated by the generator
    ///
    public partial interface ICustomersAccess<T> : Contracts.IDataAccess<T>
    {
    }
}
