//@GeneratedCode
namespace QuickTemplate.WebApi.Models.Test
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class CompanyEdit
    {
        ///
        /// Generated by the generator
        ///
        static CompanyEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public CompanyEdit()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String Name
        {
            get;
            set;
        }
        = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String Address
        {
            get;
            set;
        }
        = string.Empty;
    }
}
