//@GeneratedCode
namespace QuickTemplate.WebApi.Models.Test
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class CustomerEdit
    {
        ///
        /// Generated by the generator
        ///
        static CustomerEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public CustomerEdit()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String FirstName
        {
            get;
            set;
        }
        = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String LastName
        {
            get;
            set;
        }
        = string.Empty;
    }
}
