//@GeneratedCode
namespace QuickTemplate.Logic.DataContext
{
    ///
    /// Generated by the generator
    ///
    partial class ProjectDbContext
    {
        ///
        /// Generated by the generator
        ///
        public DbSet<QuickTemplate.Logic.Entities.Test.Company>? CompanySet
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public DbSet<QuickTemplate.Logic.Entities.Test.Customer>? CustomerSet
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        partial void GetGeneratorDbSet<E>(ref DbSet<E>? dbSet, ref bool handled) where E : Entities.IdentityEntity
        {
            if (typeof(E) == typeof(QuickTemplate.Logic.Entities.Test.Company))
            {
                dbSet = CompanySet as DbSet<E>;
                handled = true;
            }
            if (typeof(E) == typeof(QuickTemplate.Logic.Entities.Test.Customer))
            {
                dbSet = CustomerSet as DbSet<E>;
                handled = true;
            }
        }
    }
}
