//@GeneratedCode
namespace QuickTemplate.Logic.Models.Test
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class Customer
    {
        ///
        /// Generated by the generator
        ///
        static Customer()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public Customer()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        new internal QuickTemplate.Logic.Entities.Test.Customer Source
        {
            get => (QuickTemplate.Logic.Entities.Test.Customer)(_source ??= new QuickTemplate.Logic.Entities.Test.Customer());
            set => _source = value;
        }
        public System.String FirstName
        {
            get => Source.FirstName;
            set => Source.FirstName = value;
        }
        public System.String LastName
        {
            get => Source.LastName;
            set => Source.LastName = value;
        }
        public System.Collections.Generic.List<QuickTemplate.Logic.Models.Test.Company> Companies
        {
            get => Source.Companies.Select(e => QuickTemplate.Logic.Models.Test.Company.Create(e)).ToList();
            set => Source.Companies = value.Select(e => e.Source).ToList();
        }
        ///
        /// Generated by the generator
        ///
        internal void CopyProperties(QuickTemplate.Logic.Entities.Test.Customer other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                FirstName = other.FirstName;
                LastName = other.LastName;
                Companies = other.Companies.Select(e => QuickTemplate.Logic.Models.Test.Company.Create((object)e)).ToList();
                RowVersion = other.RowVersion;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QuickTemplate.Logic.Entities.Test.Customer other, ref bool handled);
        partial void AfterCopyProperties(QuickTemplate.Logic.Entities.Test.Customer other);
        ///
        /// Generated by the generator
        ///
        internal void CopyProperties(QuickTemplate.Logic.Models.Test.Customer other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                FirstName = other.FirstName;
                LastName = other.LastName;
                Companies = other.Companies;
                RowVersion = other.RowVersion;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QuickTemplate.Logic.Models.Test.Customer other, ref bool handled);
        partial void AfterCopyProperties(QuickTemplate.Logic.Models.Test.Customer other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Test.Customer other)
            {
                result = IsEqualsWith(RowVersion, other.RowVersion)
                && Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return HashCode.Combine(FirstName, LastName, Companies, RowVersion, Id);
        }
        ///
        /// Generated by the generator
        ///
        public static QuickTemplate.Logic.Models.Test.Customer Create()
        {
            BeforeCreate();
            var result = new QuickTemplate.Logic.Models.Test.Customer();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QuickTemplate.Logic.Models.Test.Customer Create(object other)
        {
            BeforeCreate(other);
            CommonBase.Extensions.ObjectExtensions.CheckArgument(other, nameof(other));
            var result = new QuickTemplate.Logic.Models.Test.Customer();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QuickTemplate.Logic.Models.Test.Customer Create(QuickTemplate.Logic.Models.Test.Customer other)
        {
            BeforeCreate(other);
            var result = new QuickTemplate.Logic.Models.Test.Customer();
            result.CopyProperties(other);
            AfterCreate(result, other);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        internal static QuickTemplate.Logic.Models.Test.Customer Create(QuickTemplate.Logic.Entities.Test.Customer other)
        {
            BeforeCreate(other);
            var result = new QuickTemplate.Logic.Models.Test.Customer();
            result.Source = other;
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QuickTemplate.Logic.Models.Test.Customer instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QuickTemplate.Logic.Models.Test.Customer instance, object other);
        static partial void BeforeCreate(QuickTemplate.Logic.Models.Test.Customer other);
        static partial void AfterCreate(QuickTemplate.Logic.Models.Test.Customer instance, QuickTemplate.Logic.Models.Test.Customer other);
        static partial void BeforeCreate(QuickTemplate.Logic.Entities.Test.Customer other);
        static partial void AfterCreate(QuickTemplate.Logic.Models.Test.Customer instance, QuickTemplate.Logic.Entities.Test.Customer other);
    }
}
