//@GeneratedCode
namespace QuickTemplate.WebApi.Controllers.Test
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class CompaniesController : Controllers.GenericController<QuickTemplate.Logic.Models.Test.Company, QuickTemplate.WebApi.Models.Test.CompanyEdit, QuickTemplate.WebApi.Models.Test.Company>
    {
        ///
        /// Generated by the generator
        ///
        static CompaniesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public CompaniesController(QuickTemplate.Logic.Contracts.Test.ICompaniesAccess<QuickTemplate.Logic.Models.Test.Company> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QuickTemplate.WebApi.Models.Test.Company ToOutModel(QuickTemplate.Logic.Models.Test.Company accessModel)
        {
            var handled = false;
            var result = default(QuickTemplate.WebApi.Models.Test.Company);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QuickTemplate.WebApi.Models.Test.Company.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QuickTemplate.Logic.Models.Test.Company accessModel, ref QuickTemplate.WebApi.Models.Test.Company? outModel, ref bool handled);
        partial void AfterToOutModel(QuickTemplate.WebApi.Models.Test.Company outModel);
    }
}
