//@GeneratedCode
namespace QuickTemplate.WebApi.Controllers.Test
{
    ///
    /// Generated by the generator
    ///
    public sealed partial class CustomersController : Controllers.GenericController<QuickTemplate.Logic.Models.Test.Customer, QuickTemplate.WebApi.Models.Test.CustomerEdit, QuickTemplate.WebApi.Models.Test.Customer>
    {
        ///
        /// Generated by the generator
        ///
        static CustomersController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public CustomersController(QuickTemplate.Logic.Contracts.Test.ICustomersAccess<QuickTemplate.Logic.Models.Test.Customer> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override QuickTemplate.WebApi.Models.Test.Customer ToOutModel(QuickTemplate.Logic.Models.Test.Customer accessModel)
        {
            var handled = false;
            var result = default(QuickTemplate.WebApi.Models.Test.Customer);
            BeforeToOutModel(accessModel, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = QuickTemplate.WebApi.Models.Test.Customer.Create(accessModel);
            }
            AfterToOutModel(result);
            return result;
        }
        partial void BeforeToOutModel(QuickTemplate.Logic.Models.Test.Customer accessModel, ref QuickTemplate.WebApi.Models.Test.Customer? outModel, ref bool handled);
        partial void AfterToOutModel(QuickTemplate.WebApi.Models.Test.Customer outModel);
    }
}
