//@GeneratedCode
namespace QuickTemplate.AspMvc.Models.Test
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class CompanyFilter : Models.View.IFilterModel
    {
        ///
        /// Generated by the generator
        ///
        static CompanyFilter()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public CompanyFilter()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String? Name
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.String? Address
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public bool HasEntityValue => Name != null || Address != null;
        private bool show = true;
        ///
        /// Generated by the generator
        ///
        public bool Show => show;
        ///
        /// Generated by the generator
        ///
        public string CreateEntityPredicate()
        {
            var result = new System.Text.StringBuilder();
            if (Name != null)
            {
                if (result.Length > 0)
                {
                    result.Append(" || ");
                }
                result.Append($"(Name != null && Name.Contains(\"{Name}\"))");
            }
            if (Address != null)
            {
                if (result.Length > 0)
                {
                    result.Append(" || ");
                }
                result.Append($"(Address != null && Address.Contains(\"{Address}\"))");
            }
            return result.ToString();
        }
        ///
        /// Generated by the generator
        ///
        public override string ToString()
        {
            return $"Name: {(Name ?? "---")} Address: {(Address ?? "---")} ";
        }
    }
}
