//@GeneratedCode
namespace QuickTemplate.AspMvc.Models.Test
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class Customer
    {
        ///
        /// Generated by the generator
        ///
        static Customer()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public Customer()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String FirstName
        {
            get;
            set;
        }
        = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String LastName
        {
            get;
            set;
        }
        = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.Collections.Generic.List<QuickTemplate.AspMvc.Models.Test.Company> Companies
        {
            get;
            set;
        }
        = new();
        ///
        /// Generated by the generator
        ///
        public static QuickTemplate.AspMvc.Models.Test.Customer Create()
        {
            BeforeCreate();
            var result = new QuickTemplate.AspMvc.Models.Test.Customer();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static QuickTemplate.AspMvc.Models.Test.Customer Create(object other)
        {
            BeforeCreate(other);
            CommonBase.Extensions.ObjectExtensions.CheckArgument(other, nameof(other));
            var result = new QuickTemplate.AspMvc.Models.Test.Customer();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(QuickTemplate.AspMvc.Models.Test.Customer instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(QuickTemplate.AspMvc.Models.Test.Customer instance, object other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(QuickTemplate.AspMvc.Models.Test.Customer other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                FirstName = other.FirstName;
                LastName = other.LastName;
                Companies = other.Companies;
                RowVersion = other.RowVersion;
                Id = other.Id;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(QuickTemplate.AspMvc.Models.Test.Customer other, ref bool handled);
        partial void AfterCopyProperties(QuickTemplate.AspMvc.Models.Test.Customer other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Test.Customer other)
            {
                result = IsEqualsWith(RowVersion, other.RowVersion)
                && Id == other.Id;
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return HashCode.Combine(FirstName, LastName, Companies, RowVersion, Id);
        }
    }
}
