//@GeneratedCode
namespace QuickTemplate.AspMvc.Models.Test
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class CustomerFilter : Models.View.IFilterModel
    {
        ///
        /// Generated by the generator
        ///
        static CustomerFilter()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public CustomerFilter()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public System.String? FirstName
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.String? LastName
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public bool HasEntityValue => FirstName != null || LastName != null;
        private bool show = true;
        ///
        /// Generated by the generator
        ///
        public bool Show => show;
        ///
        /// Generated by the generator
        ///
        public string CreateEntityPredicate()
        {
            var result = new System.Text.StringBuilder();
            if (FirstName != null)
            {
                if (result.Length > 0)
                {
                    result.Append(" || ");
                }
                result.Append($"(FirstName != null && FirstName.Contains(\"{FirstName}\"))");
            }
            if (LastName != null)
            {
                if (result.Length > 0)
                {
                    result.Append(" || ");
                }
                result.Append($"(LastName != null && LastName.Contains(\"{LastName}\"))");
            }
            return result.ToString();
        }
        ///
        /// Generated by the generator
        ///
        public override string ToString()
        {
            return $"FirstName: {(FirstName ?? "---")} LastName: {(LastName ?? "---")} ";
        }
    }
}
