//@GeneratedCode
namespace QuickTemplate.AspMvc
{
    ///
    /// Generated by the generator
    ///
    partial class Program
    {
        static partial void AddServices(WebApplicationBuilder builder)
        {
            builder.Services.AddTransient<QuickTemplate.Logic.Contracts.Test.ICompaniesAccess<QuickTemplate.Logic.Models.Test.Company>, QuickTemplate.Logic.Facades.Test.CompaniesFacade>();
            builder.Services.AddTransient<QuickTemplate.Logic.Contracts.Test.ICustomersAccess<QuickTemplate.Logic.Models.Test.Customer>, QuickTemplate.Logic.Facades.Test.CustomersFacade>();
        }
    }
}
