//@GeneratedCode
namespace QuickTemplate.Logic.Controllers.Test
{
    ///
    /// Generated by the generator
    ///
    internal sealed partial class CompaniesController : Controllers.GenericController<Entities.Test.Company>, Contracts.Test.ICompaniesAccess<Entities.Test.Company>
    {
        ///
        /// Generated by the generator
        ///
        static CompaniesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public CompaniesController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public CompaniesController(ControllerObject other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
    }
}
