//@GeneratedCode
namespace QuickTemplate.Logic.Controllers.Test
{
    ///
    /// Generated by the generator
    ///
    internal sealed partial class CustomersController : Controllers.GenericController<Entities.Test.Customer>, Contracts.Test.ICustomersAccess<Entities.Test.Customer>
    {
        ///
        /// Generated by the generator
        ///
        static CustomersController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public CustomersController()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public CustomersController(ControllerObject other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
    }
}
