//@GeneratedCode
namespace QuickTemplate.AspMvc.Controllers.Test
{
    using Microsoft.AspNetCore.Mvc;
    using TAccessModel = QuickTemplate.Logic.Models.Test.Company;
    using TViewModel = QuickTemplate.AspMvc.Models.Test.Company;
    using TFilterModel = QuickTemplate.AspMvc.Models.Test.CompanyFilter;
    using TAccessContract = QuickTemplate.Logic.Contracts.Test.ICompaniesAccess<QuickTemplate.Logic.Models.Test.Company>;
    ///
    /// Generated by the generator
    ///
    public sealed partial class CompaniesController : Controllers.FilterGenericController<TAccessModel, TViewModel, TFilterModel, TAccessContract>
    {
        ///
        /// Generated by the generator
        ///
        static CompaniesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        protected override string ControllerName => "Companies";
        ///
        /// Generated by the generator
        ///
        public CompaniesController(QuickTemplate.Logic.Contracts.Test.ICompaniesAccess<TAccessModel> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override TViewModel ToViewModel(TAccessModel accessModel, ActionMode actionMode)
        {
            var handled = false;
            var result = default(TViewModel);
            BeforeToViewModel(accessModel, actionMode, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = TViewModel.Create(accessModel);
            }
            AfterToViewModel(result, actionMode);
            return BeforeView(result, actionMode);
        }
        partial void BeforeToViewModel(TAccessModel accessModel, ActionMode actionMode, ref TViewModel? viewModel, ref bool handled);
        partial void AfterToViewModel(TViewModel viewModel, ActionMode actionMode);
    }
}
